const pangrams = {
    en: [
    `Waltz, bad nymph, for quick jigs vex.`,
    `Glib jocks quiz nymph to vex dwarf.`,
    `Sphinx of black quartz, judge my vow.`,
    `How quickly daft jumping zebras vex!`,
    `The five boxing wizards jump quickly.`,
    `Jackdaws love my big sphinx of quartz.`,
    `Pack my box with five dozen liquor jugs.`,
    `A mad boxer shot a quick, gloved jab to the jaw of his dizzy opponent.`,
    `A quart jar of oil mixed with zinc oxide makes a very bright paint.`,
    `A quick movement of the enemy will jeopardize gunboats.`,
    `About sixty codfish eggs will make a quarter pound of very fizzy jelly.`,
    `Alfredo must just bring very exciting news to the plaza quickly.`,
    `All questions asked by five watch experts amazed the judge.`,
    `Amazingly few discotheques provide jukeboxes.`,
    `Anxious Paul waved back his pa from the zinc quarry just sighted.`,
    `As we explored the gilf of Zanzibar, we quickly moved closer to the jutting rocks.`,
    `Astronaut Quincy B. Zack defies gravity with six jet fuel pumps.`,
    `Back in June we delivered oxygen equipment of the same size.`,
    `Back in my quaint garden, jaunty zinnias vie with flaunting phlox.`,
    `Ban foul, toxic smogs which quickly jeopardize lives.`,
    `Barkeep! A flaming tequila swizzle and a vodka and Ajax, hold the cherry.`,
    `Baroque? Hell, just mix a dozen wacky pi fonts and you've got it.`,
    `Bawds jog, flick quartz, vex nymphs.`,
    `Blowzy red vixens fight for a quick jump.`,
    `Brawny gods just flocked up to quiz and vex him.`,
    `By Jove, my quick study of lexicography won a prize!`,
    `Crazy Fredericka bought many very exquisite opal jewels.`,
    `Cozy lummox gives smart squid who asks for job pen.`,
    `Cozy sphinx waves quart jug of bad milk.`,
    `Crazy Fredericka bought many very exquisite opal jewels.`,
    `Dangerously frozen, he quickly judged his extremities to be waterproof.`,
    `Dental surgeon zaps sexual joker with quick-frozen Valium!`,
    `Doxy with charming buzz quaffs vodka julep.`,
    `Dr. Jekyll vows to finish zapping quixotic bum.`,
    `Dub waltz, nymph, for quick jigs vex.`,
    `Dumpy kibitzer jingles as exchequer overflows.`,
    `Ebenezer unexpectedly bagged two tranquil aardvarks with his jiffy vacuum cleaner.`,
    `Emily Q. Jung-Schwartzkopf XV, B.D.`,
    `Exquisite farm wench gives body jolt to prize stinker.`,
    `Exquisite wizard flock behaving jumpy.`,
    `Fabled reader with jaded, roving eye seized by quickened impulse to expand budget.`,
    `Few quips galvanized the mock jury box.`,
    `Five jumbo oxen graze quietly with packs of dogs.`,
    `Five or six jet planes zoomed quickly by the tower.`,
    `Five wine experts jokingly quizzed chablis sample.`,
    `Fred specialized in the job of making very quaint wax toys.`,
    `Freight to me sixty dozen quart jars and twelve black pans.`,
    `Glum Q. Scharzkopf jinxed by TV.`,
    `Grumpy wizards make toxic brew for the evil Queen and Jack.`,
    `Guzzling of jaunty exile wrecks havoc at damp banquet.`,
    `G. W. Bush quickly fixed prize jam on TV.`,
    `Hark! Toxic jungle water vipers quietly drop on zebras for meals!`,
    `His graceful bisque vase whizzed past my taxi - no joke!`,
    `How jolly vexing a fumble to drop zucchini in the quicksand!`,
    `How quickly daft jumping zebras vex.`,
    `How razorback-jumping frogs can level six piqued gymnasts!`,
    `I have quickly spotted the four women dozing in the jury box.`,
    `I was temporarily forced to zig-zag and quiver furiously around big junky xylophones.`,
    `If Jack quiz bald nymphs grow vext.`,
    `In Boston: Jazzy (but malicious) sqeak toy explodes, ending the lives of two children.`,
    `Jack amazed a few girls by dropping the antique onyx vase!`,
    `Jack Farmer realized that the big yellow quilts were expensive.`,
    `Jackdaw, love my big sphinx of quartz.`,
    `Jaded zombies acted quaintly, but kept driving their oxen forward.`,
    `Jail zesty vixen who grabbed pay from quack.`,
    `Jay visited back home and gazed upon a brown fox and quail.`,
    `Jeb quickly drove a few extra miles on the glazed pavement.`,
    `Jim just quit and packed extra heavy bags for Liz Owen.`,
    `Jimmy and Zack, the police explained, were last seen diving into a field of buttered quahogs.`,
    `Jolly housewives made inexpensive meals using quick-frozen vegetables.`,
    `Jumpy zebra vows to quit thinking coldly of sex.`,
    `Judge Powell quickly gave six embezzlers stiff sentences.`,
    `Just work for improved basic techniques to maximize your typing skill.`,
    `King Alexander was just partly overcome after quizzing Diogenes in his tub.`,
    `Lazy jackal from raiding zebec prowls the quiet cove.`,
    `Lazy movers quit hard-packing of papier-mache jewelry boxes.`,
    `Many big jackdaws zipped quickly over the fox pen.`,
    `Many-wived Jack laughs at probes of sex quiz.`,
    `Martin J. Hixeypovzer began his first word.`,
    `May Jo equal the fine record by solving six puzzles a week?`,
    `Meghan deftly picks valuable jewels: onyx, quartz.`,
    `Monique, the buxom coed, likes to fight for Pez with the junior varsity team.`,
    `Murky haze enveloped a city, as jarring quakes broke fourty-six windows.`,
    `My grandfather picks up quartz and valuable onyx jewels.`,
    `My help squeezed in and joined the weavers again before six o'clock.`,
    `Nancy Bizal exchanged vows with Robert J. Kumpf at Quincy Temple.`,
    `New farmhand proves strong but lazy, picking just six quinces.`,
    `New job: fix Mr. Gluck's hazy TV, PDQ!`,
    `Now is the time for all quick brown dogs to jump over the lazy lynx.`,
    `On the boardwalk grave playful lizards quickly jump and exercise.`,
    `Oozy quivering jellyfish expectorated by mad hawk.`,
    `Opium frequently leads to bad palpitations, hazy judgement, and causes weak sex drive.`,
    `Pack my box with five dozen liquor jugs.`,
    `Pangrams have subjects like "dewy fox quiz."`,
    `Perhaps President Clinton's amazing sax skills will be judged quite favourably?`,
    `Picking just six quinces, new farm hand proves strong but lazy.`,
    `Playing jazz vibe chords quickly excites my wife.`,
    `Prized waxy jonquils choke big farm vats.`,
    `Prodigal lesbians from Venezuela know just exactly how to eat quiche.`,
    `Puzzled women bequeath jerks very exotic gifts.`,
    `Questions of a zealous nature have become by degrees petty waxen jokes.`,
    `Quick jigs for waltz vex bad nymph.`,
    `Quick zephyrs blow, vexing daft Jim.`,
    `Quick waxy bugs jump the frozen veldt.`,
    `"Quit beer," vows dizzy, puking, Michael J. Fox.`,
    `Quizotic knights' wives are found on jumpy old zebras.`,
    `Quiz explained for TV show by Mick Jagger.`,
    `Rowdy virgins have quite often been willingly picked for prizes in juicy sex marathons.`,
    `Sexy zebras just prowl and vie for quick hot matings.`,
    `Six big devils from Japan quickly forgot how to waltz.`,
    `Six big juicy steaks sizzled in a pan, as five workmen left the quarry.`,
    `Six boys guzzled cheap raw plum vodka quite joyfully.`,
    `Six crazy kings vowed to abolish my quite pitiful jousts.`,
    `Six javelins thrown by the quick savages whizzed forty paces beyond the mark.`,
    `Six of the women quietly gave back prizes to the judge.`,
    `Six plump boys guzzled cheap raw vodka quite joyfully.`,
    `Sixty zippers were quickly picked from the woven jute bag.`,
    `Sphinx of black quartz, judge my vow.`,
    `Suez sailor vomits jauntily abaft while waxing parquet decks.`,
    `Sympathizing would fix Quaker objectives.`,
    `The exodus of jazzy pigeons is craved by squeamish walkers.`,
    `The explorer was frozen in his big kayak just after making a queer discovery.`,
    `Their kind aunt was subject to frequent dizzy spells, thus causing much anxiety and worry.`,
    `The job of waxing linoleum frequently peeves chintzy kids.`,
    `The job requires extra pluck and zeal from every young wage earner.`,
    `The jukebox music puzzled a gentle visitor from a quaint valley town.`,
    `The July sun caused a fragment of black pine wax to ooze on the velvet quilt.`,
    `The public was amazed to view the quickness and dexterity of the juggler.`,
    `The risque gown marked a very brazen exposure of juicy flesh.`,
    `The sex life of the woodchuck is a provocative question for most vertebrate zoology majors.`,
    `The vixen jumped quickly on her foe, barking with zeal.`,
    `Their kind aunt was subject to frequent dizzy spells, thus causing much anxiety and worry.`,
    `Travelling beneath the azure sky in our jolly ox-cart, we often hit bumps quite hard.`,
    `Uphill jogging will tax pounding heart muscle very quickly; better to be lazy!`,
    `Verbatim reports were quickly given by Jim Fox to his amazed audience.`,
    `Verily, the dark ex-Jew quit Zionism, preferring the cabala.`,
    `Vexed funky camp juggler quit show biz.`,
    `Victors flank gypsy who mixed up on job quiz.`,
    `Viewing quizzical abstracts mixed up hefty jocks.`,
    `Walz, nymph, for quick jigs vex Bud.`,
    `Watch all five questions asked by experts amaze the judge.`,
    `We could jeopardize six of the gunboats by two quick moves.`,
    `We crazed folk quit having sex, be jumpy.`,
    `We have just quoted on nine dozen boxes of grey lamp wicks.`,
    `We promptly judged antique ivory buckles for the next prize.`,
    `When waxing parquet decks, Suez sailors vomit jauntily abaft.`,
    `We quickly seized the black axle and just saved it from going past him.`,
    `When we go back to Juarez, Mexico, do we fly over picturesque Arizona?`,
    `Whenever the black fox jumped, the squirrel gazed suspiciously.`,
    `While making deep excavations we found some quaint bronze jewelry.`,
    `Will Major Douglas be expected to take this true-false quiz very soon?`,
    `William said that everything about his jacket was in quite good condition except for the zipper.`,
    `Wolves exit quickly as fanged zoo chimp jabbers.`,
    `Would you please examine both sizes of jade figures very quickly.`,
    `Woven silk pyjamas exchanged for blue quartz.`,
    `Xylophone wizard begets quick jive form.`,
    `You go tell that vapid existentialist quack Freddy Nitzsche that he can just bite me, twice.`,
    `You will quite often be amazed by Jock's very weighty, size six sporran!`,
    `Zany Jacques French's pub mixed watery vodka gimlets.`,
    `Zelda quickly wove eight nubby flax jumpers.`,
    ],  
    ko:[
        `다람쥐 헌 쳇바퀴에 타고파`,
        `닭 콩팥 훔친 집사`,
        `물컵 속 팥 찾던 형`,
        `동틀 녘 햇빛 포개짐`,
        `동틀 녘 햇빛 작품`,
        `자동차 바퀴 틈새가 파랗니`,
        `해태 옆 치킨집 닭맛`,
        `코털 팽 대감네 첩 좋소`,
        `닭 잡아서 치킨파티 함`,
        `초코볼은 티피가 맛 좋다`,
        `파티에 참석한 키다리 부자`,
        `펄코트 못 받은 척하자`,
        `추운 겨울에는 따뜻한 커피와 티를 마셔야지요`,
        `그는 미쳐서 칼부림하는 인성파탄자일 뿐이다`,
        `동녘 구름 틈새로 퍼지는 햇빛`,
        `콩고물과 우유가 들어간 빙수는 차게 먹어야 특별한 맛이 잘 표현된다.`,
        `참나무 타는 소리와 야경만큼 밤의 여유를 표현해 주는 것도 없다`,
        `컴퓨터 출판물의 양이 늘면 타입킷의 활용도 많아지게 된다`,
        `덧글은 통신 예절 지키면서 표현 자유 추구하는 방향으로`,
        `꽃을 잘 키우려면 수분과 윤기 먹은 토양이 필요하다`,
        `정 참판 양반댁 규수 큰 교자 타고 혼례 치른 날`
    ]
}
export default pangrams;